config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('materials/', include('materials.urls', namespace='materials')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import (contact, StudentListView, StudentDetailView,
                        StudentCreateView, StudentUpdateView,
                        StudentDeleteView, toggle_activity)

app_name = MainConfig.name

urlpatterns = [
    path('', StudentListView.as_view(), name='student_list'),
    path('contact/', contact, name='contact'),
    path('view/<int:pk>', StudentDetailView.as_view(), name='view_student'),
    path('create/', StudentCreateView.as_view(), name='create_student'),
    path('edit/<int:pk>', StudentUpdateView.as_view(), name='update_student'),
    path('delete/<int:pk>', StudentDeleteView.as_view(), name='delete_student'),
    path('activity/<int:pk>', toggle_activity, name='toggle_activity'),
]

materials/urls.py
from django.urls import path

from materials.apps import MaterialsConfig
from materials.views import (MaterialCreateView, MaterialListView, MaterialDetailView,
                             MaterialUpdateView, MaterialDeleteView)

app_name = MaterialsConfig.name

urlpatterns = [
    path('create/', MaterialCreateView.as_view(), name='create'),
    path('', MaterialListView.as_view(), name='list'),
    path('view/<int:pk>/', MaterialDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', MaterialUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', MaterialDeleteView.as_view(), name='delete'),
]

main/models.py
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class Student(models.Model):
    first_name = models.CharField(max_length=100, verbose_name='имя')
    last_name = models.CharField(max_length=100, verbose_name='фамилия')
    avatar = models.ImageField(upload_to='students/',
                               verbose_name='аватар',
                               **NULLABLE)

    is_active = models.BooleanField(default=True, verbose_name='учится')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = 'студент'
        verbose_name_plural = 'студенты'
        ordering = ('last_name',)

materials/models.py
from django.db import models


class Material(models.Model):
    title = models.CharField(max_length=150, verbose_name='название')
    body = models.TextField(verbose_name='содержимое')

    views_count = models.IntegerField(default=0, verbose_name='просмотры')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'материал'
        verbose_name_plural = 'материалы'

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import (ListView, DetailView,
                                  CreateView, UpdateView,
                                  DeleteView)

from main.models import Student


class StudentListView(ListView):
    model = Student


def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        print(f'{name} ({email}): {message}')

    context = {
        'title': 'Контакты'
    }
    return render(request, 'main/contact.html', context)


class StudentDetailView(DetailView):
    model = Student


class StudentCreateView(CreateView):
    model = Student
    fields = ('first_name', 'last_name', 'avatar')
    success_url = reverse_lazy('main:student_list')


class StudentUpdateView(UpdateView):
    model = Student
    fields = ('first_name', 'last_name', 'avatar')
    success_url = reverse_lazy('main:student_list')


class StudentDeleteView(DeleteView):
    model = Student
    success_url = reverse_lazy('main:student_list')


def toggle_activity(request, pk):
    student_item = get_object_or_404(Student, pk=pk)
    if student_item.is_active:
        student_item.is_active = False
    else:
        student_item.is_active = True

    student_item.save()

    return redirect(reverse('main:student_list'))

materials/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from materials.models import Material


class MaterialCreateView(CreateView):
    model = Material
    fields = ('title', 'body',)
    success_url = reverse_lazy('materials:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class MaterialUpdateView(UpdateView):
    model = Material
    fields = ('title', 'body',)
    success_url = reverse_lazy('materials:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('materials:view', args=[self.kwargs.get('pk')])


class MaterialListView(ListView):
    model = Material

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class MaterialDetailView(DetailView):
    model = Material

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class MaterialDeleteView(DeleteView):
    model = Material
    success_url = reverse_lazy('materials:list')

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
  </head>

  <body>

    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
            </div>
            {% include 'main/includes/inc_main_menu.html' %}
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>Album</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
      </section>

      <div class="album py-5 bg-light">
        <div class="container">

          <div class="row">
            {% block content %}
            {% endblock %}
          </div>
        </div>
      </div>

    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Наверх</a>
        </p>
        <p>&copy;2023-{% now 'Y' %}</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
  </body>
</html>

main/templates/main/contact.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                Офис МСК<br>
                Офис СПб
            </p>
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <h2>Напишите нам</h2>
            <form method="post">
                {% csrf_token %}
                <input class="form-control mb-2" name="name"/>
                <input class="form-control mb-2" name="email"/>
                <textarea class="form-control mb-2" name="message"></textarea>
                <button type="submit" class="mb-2 btn btn-primary form-control">Отправить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/includes/inc_main_menu.html
<div class="col-sm-4 offset-md-1 py-4">
    <h4 class="text-white">Меню</h4>
    <ul class="list-unstyled">
        <li><a href="{% url 'main:student_list' %}" class="text-white">Главная</a></li>
        <li><a href="{% url 'materials:list' %}" class="text-white">Материалы</a></li>
        <li><a href="{% url 'main:contact' %}" class="text-white">Контакты</a></li>
    </ul>
</div>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'main:create_student' %}">Добавить студента</a>
</div>
{% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">
                    {% if object.is_active %}
                        {{object|title}}
                    {% else %}
                        <span class="text-muted">{{object|title}}</span>
                    {% endif %}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
{% endblock %}

main/templates/main/student_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить студента "{{object.first_name}} {{object.last_name}}"?</p>
                            <button type="submit" class="btn btn-success">Подтвердить</button>
                            <a href="{% url 'main:student_list' %}" class="btn-btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        <div>
    </div>
{% endblock %}

main/templates/main/student_detail.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">

        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Информация студента
                    </h3>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Имя</td>
                            <td>{{object.first_name}}</td>
                        </tr>
                        <tr>
                            <td>Фамилия</td>
                            <td>{{object.last_name}}</td>
                        </tr>
                        <tr>
                            <td>Почта</td>
                            <td>{{object.email}}</td>
                        </tr>
                    </table>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
        <div class="col-6">
            <img src="/media/{{object.avatar}}"/>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/student_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{form.as_p}}
                            <button type="submit" class="btn btn-primary">Создать</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/student_list.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'main:create_student' %}">Добавить студента</a>
    </div>
        {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <p class="card-text">
                            {% if object.is_active %}
                                {{object|title}}
                            {% else %}
                                <span class="text-muted">{{object|title}}</span>
                            {% endif %}
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'main:view_student' object.pk %}"
                                   class="btn btn-sm btn-outline-secondary">Просмотр</a>
                                <a href="{% url 'main:update_student' object.pk %}" type="button"
                                    class="btn btn-sm btn-outline-secondary">Редакт.</a>
                                <a href="{% url 'main:delete_student' object.pk %}" type="button"
                                    class="btn btn-sm btn-outline-danger">Удал.</a>
                            </div>
                            {% if object.is_active %}
                                <a class="btn btn-warning" href="{% url 'main:toggle_activity' object.pk %}">Деактив.</a>
                            {% else %}
                                <a class="btn btn-success" href="{% url 'main:toggle_activity' object.pk %}">Актив.</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
{% endblock %}

materials/templates/materials/material_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить материал "{{object.title}}"?</p>
                                <button type="submit" class="btn btn-warning">Подтвердить</button>
                            <a class="btn-btn-warning" href="{% url 'materials:list' %}">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        <div>
    </div>
{% endblock %}

materials/templates/materials/material_detail.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Материал "{{object.title}}" ({{object.slug}})
                    </h3>
                </div>
                <div class="card-body">
                    <p>
                        {{ object.body }}
                    </p>
                </div>
                <div class="card-footer">
                    Просмотры: {{object.views_count}}
                </div>
            </div>
        </div>
        <div class="col-6">
        <img src="/media/{{ object.avatar }}" />
        </div>
    </div>
</div>
{% endblock %}

materials/templates/materials/material_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

materials/templates/materials/material_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-output=primary" href="{% url 'materials:create' %}">Добавить материал</a>
</div>
{% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">
                    {{object|title}}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'materials:view' object.pk %}"
                           class="btn btn-sm btn-outline-secondary">View<a>
                        <a href="{% url 'materials:edit' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Edit<a>
                        <a href="{% url 'materials:delete' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Delete<a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
{% endblock %}